
import type { Metadata } from "next";

import image1 from "/public/image1.webp"
import Main from "../components/main";

// Static metadata
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootPage() {
  return (
    <Main imageData={image1} content="Home Page" />
  );
}
