import { Metadata } from "next";
import Main from "../../components/main";

import image3 from "/public/image3.webp"

// Static metadata
export const metadata: Metadata = {
    title: "Reliability",
    description: "Generated by create next app",
};

export default function Reliability() {
    return (
        <div>
            <Main imageData={image3} content="Reliability Page" />
        </div>
    )
}